name: Update dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Generate requirements.txt
        run: make requirements.txt
      - uses: actions/checkout@v4
      - name: Update dependencies
        uses: pdm-project/update-deps-action@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "pdm: Update deps"
          pr-title: "pdm: Automatic dependencies update"
          update-strategy: reuse
          save-strategy: minimum
          unconstrained: false
          install-plugins: "false"
          sign-off-commit: "false"
          sign-commits: "true"
